### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by jkersu** [surudhb/gatsby-personal-site-template#3]
Hi there, great work on the template.

I have noticed that when you have a lot of articles on the Blog (for example if you had 100), it will load all the articles at once. Is there an easy way to add pagination support to the template?

I have tried as mentioned here, but ran into trouble passing in the $skip and $limit variables: https://www.gatsbyjs.com/docs/adding-pagination/

Thanks.

**Comment by surudhb** [comment]
Hello there!  Thanks for checking out the template :)

Yes, you are correct. Since all the articles are shown on the same page, the query requests all X number of posts along with its images. In order to change that, following the `adding pagination` tutorial should be enough for adding pagination to the template. There is nothing in the template that prevents it.

However, there are some things that I feel are important to keep in mind: 

1. The query for the feature images for the blog posts should also be modified (or rewritten entirely) in sync with the pagination logic for each of the blog posts.

2. If the pagination tutorial isn't working out, there might be community plugins that are able to handle this. Something like [this](https://www.digitalocean.com/community/tutorials/gatsbyjs-pagination-in-gatsby) comes to mind.

Other than that, what is the specific issue you are facing?

**Comment by surudhb** [comment]
Closing since inactive.
